version: '3.8'

services:
  db-hotel-hub:
    image: postgres:15-alpine
    container_name: db-hotel-hub 
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=hotel_hub
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge